import { Theme } from "../../Theme.slint";
import { CustomCheckbox } from "../base/custom_checkbox.slint";
import { Chip } from "../base/chip.slint";

export component BindPreviewItem inherits Rectangle {
    in-out property <bool> checked: false;
    in property <string> title;
    in property <string> time-chip-text;
    in property <string> location-chip-text;
    callback toggled(bool);
    callback time-chip-clicked();
    callback location-chip-clicked();

    background: Theme.card-bg;
    border-radius: Theme.border-radius-card;
    border-width: 1px;
    border-color: Theme.border-color;
    height: 90px;

    VerticalLayout {
        padding: 10px;
        spacing: 8px;

        HorizontalLayout {
            spacing: 10px;
            CustomCheckbox {
                checked: root.checked;
                label: root.title;
                toggled(val) => { root.toggled(val); }
            }
        }

        HorizontalLayout {
            spacing: 8px;
            padding-left: 30px;
            
            if (root.time-chip-text != "") : Chip {
                text: root.time-chip-text;
                selected: true;
                clicked => { root.time-chip-clicked(); }
            }

            if (root.location-chip-text != "") : Chip {
                text: root.location-chip-text;
                selected: false;
                clicked => { root.location-chip-clicked(); }
            }
        }
    }
}
