import { Theme } from "../../Theme.slint";
import { CustomIcon } from "custom_icon.slint";

export component ContextIndicator inherits Rectangle {
    in property <string> icon-name: "clock";
    in property <string> text;

    background: Theme.card-bg;
    border-radius: 12px;
    border-width: 1px;
    border-color: Theme.border-color;
    height: 28px;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        spacing: 6px;
        alignment: center;
        
        CustomIcon {
            icon-name: root.icon-name;
            size: 14px;
            icon-color: Theme.primary;
        }

        Text {
            text: root.text;
            color: Theme.text;
            font-family: Theme.font-family;
            font-size: 12px;
            vertical-alignment: center;
        }
    }
}
