import { Theme } from "../../Theme.slint";

export component CustomToggle inherits Rectangle {
    in-out property <bool> checked: false;
    callback toggled(bool);
    
    width: 44px;
    height: 24px;
    border-radius: 12px;
    background: root.checked ? Theme.primary : #1e2638;
    
    touch := TouchArea {
        clicked => {
            root.checked = !root.checked;
            root.toggled(root.checked);
        }
    }
    
    Rectangle {
        x: root.checked ? 22px : 2px;
        y: 2px;
        width: 20px;
        height: 20px;
        border-radius: 10px;
        background: Theme.text;
    }
}
